### GET request with a header
GET http://localhost:8080/
Accept: application/json

### DELETE request with a header
DELETE http://0.0.0.0:8080/user/ee@ee.com
Accept: application/json

###
#POST http://127.0.0.1:8080/snippets
#Content-Type: application/json
#
#{"snippet": {"text" : "mysnippet"}}